#!/bin/bash
count=1
numarfcn=0
while read line; do
        numarfcn=$((numarfcn+1))
        arfcn=$(echo 0.2*$line+890+45 | bc)
        airprobe_rtlsdr.py -f $arfcn"M" &
        tshark -i lo -a duration:10 -w ./capture/scan"$count".pcap
        pkill -f airprobe_rtlsdr.py
        pkill tshark
        generator.sh scan"$count".pcap scan"$count".csv
        parser.py scan"$count".csv
        if [ $count -eq 1 ]
        then
                count=$((count+1))
        else
                count=$((count-1))
        fi
        echo $count
        if [ $numarfcn -eq 29 ]
        then
                exit
        fi
done < $1
