#!/bin/bash
count=1
while read line; do
	arfcn=$(echo 0.2*$line+890+45 | bc)
	airprobe_rtlsdr.py -f $arfcn"M" &
	tshark -i lo -a duration:5 -w /home/zhihua/capture/capture"$count".pcap
	pkill -f airprobe_rtlsdr.py
	pkill tshark
	count=$((count+1))
	echo $count
done < $1
